name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Setup just
        uses: taiki-e/install-action@6cd13508893c0e7eab5f273c2575d3859bd7229a # v2
        with:
          tool: just

      - name: Build
        run: just build

      - name: Check
        run: just check

  release-dry-run:
    needs: build
    if: github.event_name == 'pull_request'
    permissions:
      contents: write
    uses: ./.github/workflows/release.yaml
    with:
      dry_run: true

  goreleaser-dry-run:
    needs: build
    if: github.event_name == 'pull_request'
    permissions:
      contents: write
    uses: ./.github/workflows/goreleaser.yaml
    with:
      dry_run: true

  release:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    uses: ./.github/workflows/release.yaml

  goreleaser:
    needs: release
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    uses: ./.github/workflows/goreleaser.yaml
    secrets: inherit
