name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - name: Setup just
        uses: taiki-e/install-action@c7eb1735f09259a5035e8e5d44b1406b1cddc0fb # v2
        with:
          tool: just

      - name: Build
        run: just build

      - name: Check
        run: just check

  release-dry-run:
    needs: build
    if: github.event_name == 'pull_request'
    permissions:
      contents: write
    uses: ./.github/workflows/release.yaml
    with:
      dry_run: true

  goreleaser-dry-run:
    needs: build
    if: github.event_name == 'pull_request'
    permissions:
      contents: write
    uses: ./.github/workflows/goreleaser.yaml
    with:
      dry_run: true

  release:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    uses: ./.github/workflows/release.yaml

  goreleaser:
    needs: release
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    uses: ./.github/workflows/goreleaser.yaml
    secrets: inherit
